version: '3.7'
services:
    rpisocket:
        build: '.'
        privileged: true
        environment:
            - SOCKET_PORT=${SOCKET_PORT}
        command: "sudo /data/rpisocket/build/rpisocket_test_project"
        ports: 
            - "${SOCKET_PORT}:${SOCKET_PORT}"